BackupSchedule type and db handlers
ydb-platform/ydbcp pull request #47
Opened 2024-08-23 15:35 UTC by qrort

2024-09-09 13:03 UTC, ulya-sidorina commented on internal/connectors/db/process_result_set.go
> +		lastBackupId            *string
`lastBackupId` -> `lastBackupID` and  `lastSuccessfullBackupId` -> `lastSuccessfullBackupID`

2024-09-10 08:40 UTC, bma13 requested changes

2024-09-10 08:40 UTC, bma13 commented on internal/server/services/backup_schedule/backup_schedule_service.go
> +	panic("implement me")
`return nil, status.Error(codes.Internal, "not implemented")`

2024-09-10 08:40 UTC, bma13 commented on internal/server/services/backup_schedule/backup_schedule_service.go
> +	panic("implement me")
`return nil, status.Error(codes.Internal, "not implemented")`

2024-09-10 22:41 UTC, bma13 approved these changes

2024-09-10 22:41 UTC, merged